project:
  type: website

website: 
  image: rstudio-logo.png
  
format:
  html:
    comments:
      hypothesis: true
    toc: true
    echo: false
    code-fold: true 
  beamer:
    beamerarticle: false

# execute:
#   freeze: auto

editor: visual

lang: de

