project:
  type: website
  output-dir: docs

website: 
  image: rstudio-logo.png
  
  
format:
  html:
    comments:
      hypothesis: true
    embed-resources: true
    toc: true
    echo: false
    code-fold: true 
    
  beamer:
    beamerarticle: false

# execute:
#   freeze: auto

editor: visual

lang: de

